### ISSUE TITLE
Document that user, password, and db name should be urlencoded

### ISSUE THREAD

**Issue by melinath** [jazzband/dj-database-url#108]
I ran into an issue today deploying usage of dj-database-url to production, which had a password that included a non-url-safe character. Since putting usernames / passwords into urls is not something I've done a lot of, I didn't know that quoting was necessary (and I wasn't even sure it would work.)

I ended up finding this web page, which mentioned that quoting was needed: https://support.brightcove.com/special-characters-usernames-and-passwords

The error I got was:

```
File "/usr/lib/python2.7/urlparse.py", line 214, in urlsplit
    raise ValueError("Invalid IPv6 URL")
```

It would be great if the documentation for dj-database-url could include a note about this. It doesn't seem like there would be a good way to catch this error and re-raise with more helpful information, unfortunately, but if I'm mistaken then that would also be great.

**Comment by mattseymour** [comment]
This requirement has been added to the readme.rst in commit 836740dd814878c
