### ISSUE TITLE
Document how to specify local MySQL db 

### ISSUE THREAD

**Issue by trodicaro** [jazzband/dj-database-url#112]
DATABASES['default'] =  dj_database_url.config(default="mysql://myname:mypass@localhost:3306/db_name") works.

**Comment by douglaspetrin** [comment]
@trodicaro did you just remove the dict DATABASES = { } ?

in your settings.py you just added this line?

DATABASES['default'] = dj_database_url.config(default="mysql://myname:mypass@localhost:3306/db_name")

**Comment by mattseymour** [comment]
This is an old issue closing it off. If you feel this is still a requirement please create a new ticket.
