### ISSUE TITLE
See about moving this to an official Django project

### ISSUE THREAD

**Issue by jacobian** [jazzband/dj-database-url#120]
Given the widespread use of dj-database-url, it seems a good idea for it to become [Official Project, per DEP 7](https://github.com/django/deps/blob/master/final/0007-official-projects.rst#pre-proposal). Maintenance burden seems minimal but important.

Read DEP 7 for full details, but roughly there are 4 steps:

1. Pre-proposal discussion
2. Form a team
3. Formal proposal
4. Django Technical Board Vote

Let's use this thread to tackle (1) and (2). This means we need to

> work out if there is rough agreement that the project is a good thing for Django to adopt, particularly focusing on any alternative approaches to the same problem and the relative merits of them, including code design, scalability, alignment with existing Django design and philosophy, and having an available development and maintenance team.

What do folks thing?

Also: I'll be the shepherd for this proposal, but for it to go forward we'd need a larger maintenance team than just me. If there's anyone -- Django committer or not -- who would be willing to commit to long-term maintenance, please ✋ raise your hand here.

[Backstory, and why this is living on my personal github right now. @kennethreitz was looking for a new maintainer, and reached out to me to see if Django might be interested. I thought perhaps so, and offered to take over maintainership in the meantime while we work through the DEP 7 process. If it turns out that an Official Project is the wrong home for this, I'll either maintain it long-term or transfer it again.]

**Comment by ParthS007** [comment]
I am in. ✋

**Comment by jacobian** [comment]
(I've also xposted this to the django-developers mailing list)

**Comment by kobayashi** [comment]
I do also! ✋

**Comment by mattseymour** [comment]
I ✋

**Comment by jacobian** [comment]
So - no huge blockers turned up in the pre-discussion, so I think we can move forward. 

@kobayashi @mattseymour @ParthS007 - thanks for offering to help! Next steps for you (and anyone else following along who'd likewise like to help maintain):

- Please take a quick peek at #121 and make sure you're OK with that direction. 
- I'll add y'all as contributors here shortly, so we can start working together ahead of officially moving this to django/dj-database-url.
- We should start writing an official proposal. If one of y'all wants to get started on this (we could just use the wiki here for it), that would be lovely. Otherwise I'll work on it in a bit.
- I'd love to close out all open issues and PRs before we do the transfer, so that we're moving over to an official project with the cleanest possible state. I'm working through that now, and would love your help.

**Comment by ParthS007** [comment]
@jacobian I have added my [comment](https://github.com/jacobian/dj-database-url/issues/121#issuecomment-514651517) on #121

For the proposal, It would be great if you can help me(us) with some links on how to write an official proposal or you can start then I will add on it.

For Closing the open Issues, I am looking at #107 & #108 and will be making PRs If I find any workaround for them.

**Comment by jacobian** [comment]
@ParthS007 lovely, thanks!

For official projects - the proposal doesn't need to be super-long, but it should address the questions covered in [DEP 7](https://github.com/django/deps/blob/master/final/0007-official-projects.rst), particularly those that the TB will consider:

> The Technical Board should consider:
>
> * If the project's adoption would benefit Django.
> * If by adopting they are crowding out other, potentially superior solutions.
> * If the maintenance team is sufficient to ensure the project will be maintained properly once adopted.
> * If the adoption of the project would place undue stress on the existing core team.
> * If adopting the project projects the right image and message about what Django is.

For prior art, you may want to see the following threads:

* https://groups.google.com/forum/#!msg/django-developers/XwQ6Oqegjv8/rqbBb-a-AAAJ
* https://groups.google.com/d/msg/django-developers/24DGLVVRV_s/4WmgAALKAgAJ

**Comment by ParthS007** [comment]
@jacobian Any updates on this?

**Comment by prosper1** [comment]
update on this.

**Comment by mattseymour** [comment]
This project is now part of Jazzband and there for makes is ticket invalid.
