### ISSUE TITLE
Adopt the Django Code of Conduct

### ISSUE THREAD

**Issue by jacobian** [jazzband/dj-database-url#121]
I plan to adopt the [Django Code of Conduct](https://www.djangoproject.com/conduct/) for contributors to this repo. This is a sort of prerequisite to making this an official project (#120) -- that is, once it's an official project it'll inherit that CoC automatically, so we might as well do it right away. It's also the right thing to do.

This issue is an opportunity to provide feedback before I make this change, especially for folks who think they might want to be maintainers long-term (again see #120). *I plan on adopting the code of conduct one week from today, on July 31st.*

A couple of ground rules if you want to participate:

1. We're here to discuss tactics, not values. This isn't a place to debate whether CoC in general are a good idea or not. Assume that they are a good thing and proceed from there.
2. Trolling, and especially [sealioning](https://en.wikipedia.org/wiki/Sealioning), isn't ok. I'll try to be charitable about folks with questions, but if I think you're asking questions in bad faith I'm not going to engage.

These kinds of discussions can attract pretty crummy behavior, so I'm going to moderate fairly strictly.  I may lock the thread if Reddit or HN arrives in force. Sorry in advance if that happens.

**Comment by ParthS007** [comment]
@jacobian I have read the [ Django Code of Conduct ](https://www.djangoproject.com/conduct/). I am fine with that and I support all the points mentioned in the conduct.

**Comment by mattseymour** [comment]
I am a fan of the Django code of conduct, adopting it for this project seems more than reasonable given that it could be an official project before long. 

I am also +1 with regards to:
> These kinds of discussions can attract pretty crummy behavior, so I'm going to moderate fairly strictly. I may lock the thread if Reddit or HN arrives in force. Sorry in advance if that happens

**Comment by kobayashi** [comment]
Thanks @jacobian !
I have read [Django Code of Conduct](https://www.djangoproject.com/conduct/).

**Comment by mattseymour** [comment]
We are now part of jazzband which has a code of conduct. Closing as now invalid.
