### ISSUE TITLE
How would I configure a database URL for ssl?

### ISSUE THREAD

**Issue by mnowak-umich** [jazzband/dj-database-url#127]
My database requires an options value like:

'OPTIONS':  {
                'ssl': {
                   'ssl-ca': 'path to CA pem',
                   'cert': path to cert pem',
                   'key': path to key pet',
                 },
                 'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
                 'charset': 'utf8mb4'
             }

I see you have some code for ssl-ca but I am not not sure how to create a URL to handle these other options, especially when used in conjunction with Django-configurations.

**Comment by michealjroberts** [comment]
I've just had this issue myself. I think it may be something like: 

```
DATABASES['default'] = dj_database_url.config(ssl_require=True)

DATABASES['default'] = dj_database_url.parse(POSTGRES_URL, conn_max_age=600)
```

But I think yes. This needs more clarity in the docs as to how we do this?

**Comment by michealjroberts** [comment]
Ok, so update: this worked for me:

```
POSTGRES_URL = 'postgres://{}:{}@{}:{}/{}'.format(
        os.environ.get('DJANGO_POSTGRES_USER'),
        os.environ.get('DJANGO_POSTGRES_PASS'),
        os.environ.get('DJANGO_POSTGRES_HOST'),
        os.environ.get('DJANGO_POSTGRES_PORT'),
        os.environ.get('DJANGO_POSTGRES_NAME')
)

DATABASES['default'] = dj_database_url.parse(POSTGRES_URL, conn_max_age=600, ssl_require=True)```

**Comment by sshishov** [comment]
Not working for MySQL, as the connection is not secure.

**Comment by mattseymour** [comment]
Making as closed. If any more support is required please open a new ticket.

**Comment by anentropic** [comment]
From reading the README, which shows passing additional kwargs to the parse call like:

```python
DATABASES['default'] = dj_database_url.config(
    conn_max_age=600,
    conn_health_checks=True,
)
```

...I was expecting to be able to pass arbitrary values like `OPTIONS` dict the same way, e.g

```python
DATABASES['default'] = dj_database_url.config(
    conn_max_age=600,
    conn_health_checks=True,
    options={
        "charset": "utf8mb4",
    },
)
```

But actually only specific keyword args are supported.

What is not clear without reading src code is that `OPTIONS` are passed via the querystring of the url.
