### ISSUE TITLE
Is this repo still active? 

### ISSUE THREAD

**Issue by dabeeeenster** [jazzband/dj-database-url#134]
We're having [PR's](https://github.com/BulletTrainHQ/bullet-train-api/pull/48) sent to our project that uses this library but the fix would be more appropriate upstream here. If we supplied a PR to this project is it possible to have it merged and a new PyPi library pushed? 

We'd be happy to help with the management of this library if that is a help? [We use it](https://www.bullet-train.io/) and would be happy to contribute!

**Comment by mattseymour** [comment]
Yes, it is still active. We have recently move this project to Jazzband. Expect to see updated in the coming days, weeks and months.
