### ISSUE TITLE
Adding type hints

### ISSUE THREAD

**Issue by sbdchd** [jazzband/dj-database-url#135]
I was wondering if you'd be open to adding type hints to the repo?

Otherwise, would it be okay if I added them to https://github.com/python/typeshed/

**Comment by XF-FW** [comment]
Hey @sbdchd . Since, you got no reply after 2 years, could you add the types you've setup on kodiak to the typeshed? 

If you would prefer, I could do it as well, but since it's your code, I think you should do it. Just let me know! 

Thank you!

**Comment by sbdchd** [comment]
@XF-FW feel free to do it!

**Comment by mattseymour** [comment]
I think with where python is no Adding type hints is a good shout. All the supported python version are now typehint compliant.

**Comment by XF-FW** [comment]
As of earlier today, you can now have typing for this package, by installing the `types-dj-database-url` package.

**Comment by palfrey** [comment]
https://github.com/jazzband/dj-database-url/pull/198 adds in type hints (and mypy checks for them)

**Comment by XF-FW** [comment]
Could you let me know when this gets released, so I can deprecate the `types-dj-database-url` package from typeshed as per their policy[0] ?

[0] https://github.com/python/typeshed/blob/main/CONTRIBUTING.md#third-party-library-removal-policy

**Comment by palfrey** [comment]
@mattseymour Can we do a new release with this in?

**Comment by mattseymour** [comment]
I will take into doing this shortly
