### ISSUE TITLE
Is it possible to push latest version to pypi?

### ISSUE THREAD

**Issue by mqpc** [jazzband/dj-database-url#136]
Hi,

current version in pypi is `0.5.0` as well as here at master. 
Is it possible to bump the version here and release it to pypi? 🙏 

Thanks in advance!

**Comment by blayzen-w** [comment]
It looks like with Django 3.1 they fully removed postgresql_psycopg2 causing version 0.5.0 to no longer work. A new version would be greatly appreciated.

**Comment by mattseymour** [comment]
We are on the case of this at the moment. Hopefully a new release will be done in the week. We just need to co-ordinate a few things.

**Comment by XF-FW** [comment]
Hey there. Sorry to be bumping a close thread, but since the last expected date was a no-go, I was wondering if there is there an expected date for the PyPI release? 

Thank you.

**Comment by mattseymour** [comment]
Wip just need to set up github action. Sorry for delay.
