### ISSUE TITLE
Reading .pgpass for a Postgresql connection

### ISSUE THREAD

**Issue by krzysztofjeziorny** [jazzband/dj-database-url#140]
Is there a way to read the `.pgpass` file for the database connection?

https://www.postgresql.org/docs/12/libpq-pgpass.html

**Comment by TravellerSam** [comment]
(Closed accidentally.)

**Comment by dcwatson** [comment]
I'm not sure if you mean just for looking up passwords, or for reading a full `DATABASES` config out of, but either way I think this is probably out of scope for this project. There are some Python packages to read/parse `.pgpass` files, but the tricky thing is that `.pgpass` files allow for wildcards and multiple entries. We will however support overriding configuration options to make this easier in the (hopefully) near future, i.e. `parse("postgresql://user@host/db", PASSWORD=readpgpass())`.
