### ISSUE TITLE
Add github workflows for checking contributing guidelines

### ISSUE THREAD

**Issue by ParthS007** [jazzband/dj-database-url#163]
- [ ] Add pylint spec check

- [x] Add Black and flake8 check

I would like to work on it.

**Comment by jezdez** [comment]
This has already partially been done via [pre-commit](https://github.com/jazzband/dj-database-url/blob/master/.pre-commit-config.yaml) and using [pre-commit.ci](https://pre-commit.ci). You may want to add a pylint pre-commit hook, if you'd like though.

**Comment by jezdez** [comment]
Here's how it looked for #162:

![CleanShot 2022-05-25 at 12 41 54@2x](https://user-images.githubusercontent.com/1610/170244379-72027eaf-d573-468c-ad0d-687b5edfbc9b.png)

**Comment by ParthS007** [comment]
okay, thanks. I will add for pylint check. thanks

**Comment by mattseymour** [comment]
So I have no issue with pylint but we are running flake8 on the code base. But, will pylint really give us much more? Flake8 seems to be the goto tool for Jazzband projects. I worry it will be too strict and we will then start getting into configuration wars as each person has their own setup and way of doing things. Flake8 seems like a sensible compromise? What are your thoughts?

This is part of the reason flake8 was originally chosen as it seems to be a happy middle ground.

**Comment by ParthS007** [comment]
I agree with having a minimal setup for configuration, I created the issue because it was mentioned [here](https://github.com/jazzband/dj-database-url#contributing-code). We can go with having isort, black and flake8 only.

After running pylint, it shows some valid warnings which can be changed/improved without having the pre commit check as well and not to have strictness for config. I can work on them in a different PR and close this one?

**Comment by mattseymour** [comment]
I think thats probably a good shout for the time being. Becuase the project is so small I think trying to keep to a simple core set (as in other jazzband projects) seems sensible. But certainly do target the valid issues you have foud in pylint. 👍🏾
