### ISSUE TITLE
App returns Gateway Timeout when DEBUG = False

### ISSUE THREAD

**Issue by fabiodeabreuaraujo** [jazzband/dj-database-url#176]
Hi,

I recently deployed a Django app using dj-database-url, but I'm facing a very unexpected behavior: when I try to create a user with `DEBUG = True` it creates normally, but when I switch to False for production the request times out.

Is this related to dj-database-url? Can you help me out here?

Thanks!
Fábio.

**Comment by mattseymour** [comment]
Strange this would be affecting things. Is there an stacktrace?

**Comment by mattseymour** [comment]
Close due to lack of activity. If this is still an issue please provide some additional information to help debug.
