### ISSUE TITLE
Exception while using the connection string with postgres

### ISSUE THREAD

**Issue by zugspitze** [jazzband/dj-database-url#186]
Hi, I am getting the following exception when using the connection string. 

`    engine = SCHEMES[url.scheme] if engine is None else engine
KeyError: 'postgresql+psycopg2'`

Also my connection string starts with `postgresql+psycopg2`

Can you please suggest me how to fix it?
Thanks!

**Comment by mattseymour** [comment]
Do you have any more context around this issue?

**Comment by palfrey** [comment]
Two PRs for this:
* https://github.com/jazzband/dj-database-url/pull/196 makes the error a lot clearer
* https://github.com/jazzband/dj-database-url/pull/197 supports the actual schema case

**Comment by mattseymour** [comment]
The connector for postgres connections is `postgres` no need to use the `+psycopg` connection part. This is because under the hood it uses the same Django postgres connector. I would say we do not support adding aliases and instead improve the error handling. As I see @palfrey has suggested in another message.

**Comment by palfrey** [comment]
> The connector for postgres connections is `postgres` no need to use the `+psycopg` connection part. This is because under the hood it uses the same Django postgres connector. I would say we do not support adding aliases and instead improve the error handling. As I see @palfrey has suggested in another message.

Happy for me to merge https://github.com/jazzband/dj-database-url/pull/196 then?

**Comment by palfrey** [comment]
@zugspitze With the current master branch of this repo, you should now get a better error message, and so should be clear to change the schema to `postgres` now.
