### ISSUE TITLE
config() got an unexpected keyword argument 'conn_health_checks'

### ISSUE THREAD

**Issue by salomvary** [jazzband/dj-database-url#195]
Seems like the `conn_health_checks` argument to `config()` has not been included in the 1.1.0 release: https://github.com/jazzband/dj-database-url/commit/d2e4719a8da156a70d6f7682d6dfa70c5c1b903b#diff-77d67b12ae6aa3d5127deda56d99797d2ab0dbe2d03d62308eb1e26df7e4531dR53

**Comment by mattseymour** [comment]
[1.2.0](https://pypi.org/project/dj-database-url/1.2.0/) release is live.

**Comment by salomvary** [comment]
> [1.2.0](https://pypi.org/project/dj-database-url/1.2.0/) release is live.

Thanks a lot! 🍾
