### ISSUE TITLE
[mypy] Argument "conn_max_age" to "parse" has incompatible type "None"; expected "int"  [arg-type]

### ISSUE THREAD

**Issue by lorddaedra** [jazzband/dj-database-url#209]
mypy
Argument "conn_max_age" to "parse" has incompatible type "None"; expected "int"  [arg-type]

None value should be allowed for conn_max_age, proof:
https://docs.djangoproject.com/en/dev/ref/settings/#conn-max-age

**Comment by mattseymour** [comment]
Fair point we should support this correctly.
