### ISSUE TITLE
Password with special character '#' not parsing correctly

### ISSUE THREAD

**Issue by MattijsLootensRenson** [jazzband/dj-database-url#224]
Given a connection string:
`connstr="postgres://user:pass#word@server.host.com/pgsqldb"`
Parsing the given string with `dj_database_url.parse(connstr)` raises the following ValueError
`ValueError: Port could not be cast to integer value as 'pass'`
I'm guessing it just cuts the connection string starting at the '#'.

**Comment by estahn** [comment]
@MattijsLootensRenson Just stumbled across this myself. The README states:
![image](https://github.com/jazzband/dj-database-url/assets/362174/d21873bd-be01-42df-8e2b-8e777c674097)

**Comment by MattijsLootensRenson** [comment]
Must have overlooked that, thank you for the info!
