### ISSUE TITLE
Missing changelog for dj-database-url 2.2.0

### ISSUE THREAD

**Issue by Flimm** [jazzband/dj-database-url#250]
dj-database-url 2.2.0 has been released on PyPI, but [the changelog](https://github.com/jazzband/dj-database-url/blob/master/CHANGELOG.md) does not contain an entry for this version. This would be handy to have.

**Comment by lino** [comment]
Thank you for noticing, I have added the changelog.

**Comment by Flimm** [comment]
Thank you so much!
