### ISSUE TITLE
Allow colons (%3A) in percent-encoded paths

### ISSUE THREAD

**Issue by jdp** [jazzband/dj-database-url#66]
Postgres supports percent-encoded paths to allow for connecting to the DB over a domain socket since [this change](https://github.com/kennethreitz/dj-database-url/pull/29), and it would be super helpful to allow percent-encoded colons as well. That way, dj-database-url could be used with [Google Cloud SQL](https://cloud.google.com/sql/), because its socket names are in the format `/cloudsql/{project-id}:{sql-instance-id}`. Without percent-encoding the colon, it gets interpreted as an invalid port. Adding it would support connection strings like this, like Postgres:

```
>>> dj_database_url.parse('mysql://root@%2fcloudsql%2fproject-id%3asql-id/database')
{'ENGINE': 'django.db.backends.mysql', 'HOST': '/cloudsql/project-id:sql-id', 'NAME': 'database', 'CONN_MAX_AGE': 0, 'PASSWORD': '', 'PORT': '', 'USER': 'root'}
```

I have an existing patch if that would be helpful.

**Comment by kennethreitz** [comment]
A patch would be great.

**Comment by palfrey** [comment]
Implemented by https://github.com/jazzband/dj-database-url/pull/181 which is now merged
